[project]
name = "crohn-disease-llm-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.17",
    "ollama>=0.5.3",
    "streamlit>=1.48.1",
]
